version: '3.9'

services:
  foodvault_db:
    image: postgres:latest
    container_name: foodvault_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - foodvault_db_vol:/data/foodvault_db
    ports:
      - "5432:5432"

  foodvault_api:
    image: foodvaultapi
    container_name: foodvault_api
    build:
      dockerfile: FoodVault_Api/Dockerfile
    depends_on:
      - foodvault_db
    environment:
      - ConnectionString=host=foodvault_db;port=5432;database=FoodVault;username=developer;password=password;Pooling=true;
    ports:
      - "5000:80"

  foodvault_web:
    image: foodvaultweb
    container_name: foodvault_web
    build:
      dockerfile: FoodVault_Web/Dockerfile
    depends_on:
      - foodvault_api
    ports:
      - "5173:5173"
    volumes:
      - '/app/node_modules'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on:
      - foodvault_db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_SERVER_JSON_FILE: ./tools/pgadmin/servers.json
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./tools/pgadmin:/tools/pgadmin

volumes:
  foodvault_db_vol:
  pgadmin-data: